### ISSUE TITLE
key是否过期了?

### ISSUE THREAD

**Issue by SunRain** [PaperAirplane-Dev-Team/BlackLight#1152]
使用
https://open.weibo.cn/oauth2/authorize?client_id=211160679&response_type=token&redirect_uri=http://oauth.weico.cc&key_hash=1e6e33db08f9192306c4afa0a61ad56c&packagename=com.eico.weico&display=mobile&scope=email,direct_messages_read,direct_messages_write,friendships_groups_read,friendships_groups_write,statuses_to_me_read,follow_app_official_microblog,invitation_write

在桌面浏览器尝试登入的时候,点击登入按钮以后出现错误页面

An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, tengine.

**Comment by SunRain** [comment]
还是weico的服务器挂了?

**Comment by PeterCxy** [comment]
这个不是key的问题，是redirect url挂了，这个对客户端是没有影响到

**Comment by SunRain** [comment]
那请问这个要如何解决？最近在做其他平台的微博客户端，用的是weico的api（其实调用方式就是从blacklight里面扣出来的），出现这个错误以后没法得到token了

**Comment by xavieryao** [comment]
把各步http header发一下咯

发自我的 iPhone
