### ISSUE TITLE
请教下redirect uri挂掉的解决方式

### ISSUE THREAD

**Issue by SunRain** [PaperAirplane-Dev-Team/BlackLight#1155]
之前的issue关掉了。
最近在做其他平台的微博客户端，用的是weico的api（其实调用方式就是从blacklight里面扣出来的），现在出现这个错误以后似乎没法得到token了，不知道如何解决。

**Comment by xavieryao** [comment]
发一下各步的header咯

发自我的 iPhone

**Comment by SunRain** [comment]
什么header?
就是简单webview使用这个地址访问授权页面
https://open.weibo.cn/oauth2/authorize?client_id=211160679&response_type=token&redirect_uri=http://oauth.weico.cc&key_hash=1e6e33db08f9192306c4afa0a61ad56c&packagename=com.eico.weico&display=mobile&scope=email,direct_messages_read,direct_messages_write,friendships_groups_read,friendships_groups_write,statuses_to_me_read,follow_app_official_microblog,invitation_write

**Comment by SunRain** [comment]
好吧,看来是我的问题,即使redirect uri挂掉了,也可以在监听webview加载失败的时候得到token(之前一直都是监听的加载成功状态时候的返回值)
