### ISSUE TITLE
微博页面中三点菜单重复

### ISSUE THREAD

**Issue by BeetMan** [PaperAirplane-Dev-Team/BlackLight#1473]
![screenshot_2015-08-06-12-55-37](https://cloud.githubusercontent.com/assets/7609633/9104135/b7a1d406-3c3a-11e5-8047-533aa6df17b6.png)
图示的界面中3-dot-menu明显重复了

**Comment by Harry-Chen** [comment]
@PeterCxy  去掉内部的吧
