### ISSUE TITLE
[Feedback] 允许关闭某些类型（私信/at/评论）的推送通知

### ISSUE THREAD

**Issue by sttan** [PaperAirplane-Dev-Team/BlackLight#1754]

**Comment by chengyuhui** [comment]
@PeterCxy 其实我想尝试把这个做了来着..
但是还没想好怎么保存配置数据

**Comment by Harry-Chen** [comment]
You can try it, as we welcome pull requests anyway.
Use Preferences framework(we wrote a Settings class as a wrapper) to save your configurations.

发自我的 iPad

**Comment by chengyuhui** [comment]
Should I use something like JSON to save them or just use notification_cmt,notification_dm,etc. ?

**Comment by chengyuhui** [comment]
@PeterCxy This can be closed.
