### ISSUE TITLE
[Feedback] 深色主题下私信输入框显示问题

### ISSUE THREAD

**Issue by chengyuhui** [PaperAirplane-Dev-Team/BlackLight#1778]
![screenshot_2015-10-31-22-21-12](https://cloud.githubusercontent.com/assets/1381736/10867302/b86668a8-8095-11e5-9bc7-8c3240bfbaed.png)

如图，白底白字不太好用啊..

**Comment by Harry-Chen** [comment]
感谢，会修改的。
