### ISSUE TITLE
[Feedback] 求通知内容预览

### ISSUE THREAD

**Issue by chengyuhui** [PaperAirplane-Dev-Team/BlackLight#1779]
如题，希望能够有类似于官方的通知内容预览，而不是“x条新评论“

感谢

**Comment by Harry-Chen** [comment]
是这样的，如果有预览的话会造成后台拉取的内容增加很多，可能导致数据流量和耗电量增加。
如果有空的话我们可能会实现这个功能并提供相应设置项。
P.S.nickname感人啊我还以为是我自己…

**Comment by chengyuhui** [comment]
流量爆炸的可能性倒是确实有，有个选项也好23333

**Comment by chengyuhui** [comment]
@Harry-Chen 话说怎么在Service里面刷新缓存....感觉直接做的话会爆炸

**Comment by PeterCxy** [comment]
这就是我不做的原因。。我不想在后台service拉取太多数据

**Comment by Harry-Chen** [comment]
@chengyuhui 炸是必然的。。
