### ISSUE TITLE
[Feedback] 表情符号显示失效

### ISSUE THREAD

**Issue by chengyuhui** [PaperAirplane-Dev-Team/BlackLight#1780]
![screenshot_2015-11-01-15-26-03](https://cloud.githubusercontent.com/assets/1381736/10867726/451ad89e-80ad-11e5-9c3d-d716eee19f64.png)

如图，这种情况会随机出现，感觉没有什么规律

**Comment by PeterCxy** [comment]
规律是如果从通知栏进去就很可能这样

**Comment by chengyuhui** [comment]
2333333这是什么原理
