### ISSUE TITLE
ANR in ReminderService

### ISSUE THREAD

**Issue by chengyuhui** [PaperAirplane-Dev-Team/BlackLight#1854]
My fault.

Will fix soon.

Should I use Runnable/Thread?

**Comment by PeterCxy** [comment]
use AsyncTask

**Comment by PeterCxy** [comment]
info.papdt.blacklight.support.AsyncTask

**Comment by chengyuhui** [comment]
Since the timeout is less than 1min... can I just let them run without blocking the main thread?

**Comment by PeterCxy** [comment]
So just use AsyncTask.
