### ISSUE TITLE
new logo for black light

### ISSUE THREAD

**Issue by ibnu-djamil** [PaperAirplane-Dev-Team/BlackLight#2518]
I've created a new logo for flash light.
if you want to use it i will send the file.

![Logopit_1525350225100.png](https://steemitimages.com/DQmRa6foAUGt4Qhum1CCkgHTz5JEnSfo1xtqihRMSwvWoWp/Logopit_1525350225100.png)

**Comment by PeterCxy** [comment]
Thank you for your interest in this project. However, this project has long been dead and is no longer maintained anymore. We suggest you to choose another better Weibo client instead of this one.
