### ISSUE TITLE
import后出错， Gradle DSL method not found: 'runProguard()

### ISSUE THREAD

**Issue by syswow** [PaperAirplane-Dev-Team/BlackLight#839]
Error:(20, 0) Gradle DSL method not found: 'runProguard()'
Possible causes: The project 'BlackLight-master' may be using a version of Gradle that does not contain the method.
  Gradle settings 
The build file may be missing a Gradle plugin.
  Apply Gradle plugin 

EDIT 1:
可以使用minifyEnabled代替runProguard。
http://stackoverflow.com/questions/27078075/gradle-dsl-method-not-found-runproguard

**Comment by PeterCxy** [comment]
gradle 1.12 required.

**Comment by xavieryao** [comment]
And toucan simply add prefix '//' to that line. 

发自我的 iPhone

**Comment by PeterCxy** [comment]
为什么我的AS打开就没问题。。我在Travis CI上跑的gradle1.12也没问题@xavieryao

**Comment by syswow** [comment]
@PeterCxy  和AS的版本有关吧， 新版本不支持gradle1.12了。

**Comment by xavieryao** [comment]
现在的AS要Gradle 2.? 而且我还没能在AS里成功编译head

发自我的 iPhone

**Comment by syswow** [comment]
我导入的时候出现
Error:The project is using an unsupported version of the Android Gradle plug-in (0.12.2). The recommended version is 1.0.0. Fix plugin version and re-import project

**Comment by syswow** [comment]
新的 Android Gradle plug-in 只支持 Gradle V2.2.1及其后的版本。
http://tools.android.com/tech-docs/new-build-system/migrating-to-1-0-0
