### ISSUE TITLE
Migrate to Android Gradle Plugin 1.0.0

### ISSUE THREAD

**Issue by xavieryao** [PaperAirplane-Dev-Team/BlackLight#861]
Otherwise we cannot build it in Android Studio 1.0.2+   
But this means we have to re-configure Travis CI.  
The head of branch `android_gradle_1.0` works in the latest Android Studio with Gradle 2.1.1 (On my computer :-) )

**Comment by xavieryao** [comment]
Travis CI now works.

**Comment by syswow** [comment]
LGTM!

**Comment by xavieryao** [comment]
What....

发自我的 iPhone
