### ISSUE TITLE
Weico全系列的app key都已经更换

### ISSUE THREAD

**Issue by PeterCxy** [PaperAirplane-Dev-Team/BlackLight#888]
求抓包，求解。

**Comment by xavieryao** [comment]
午夜之前吧

发自我的 iPhone

**Comment by PeterCxy** [comment]
我已经通过中间人攻击搞到了新的授权信息，等会push上来，但是授权信息我会扔进私有版本库里面

**Comment by xavieryao** [comment]
为啥不用oauth?我刚抓了Weico iPhone,就是普通的OAuth用WebView就可以啊……

**Comment by xavieryao** [comment]
@PeterCxy 你说的“新的授权信息”是什么？

**Comment by xavieryao** [comment]
@PeterCxy We need to talk……

**Comment by xavieryao** [comment]
@PeterCxy 你手机没有推送吗？
