### ISSUE TITLE
关于回复用户反馈

### ISSUE THREAD

**Issue by Harry-Chen** [PaperAirplane-Dev-Team/BlackLight#982]
在此地回复的话大多数不用GH的用户显然是看不见的。
我在想能否给机器人加一个功能，在某Issue的回复中检测到特定指令时则在微博上@出该用户进行回复。
似乎hook是可以推送这个东西的（Issue Comment）

还有，那些该死的Label能去掉吗……没有更好的标记方法了吗！

**Comment by xavieryao** [comment]
在服务器弄数据库

发自我的 iPhone

**Comment by PeterCxy** [comment]
good idea

**Comment by Harry-Chen** [comment]
好了
以后在feedback里面要把什么反馈给用户的话把要说的用^包围起来就好
^Like this^
不过小心字数限制哦
@PeterCxy @xavieryao
