### ISSUE TITLE
[Feedback]  别理我我就是试试新功能

### ISSUE THREAD

**Issue by Harry-Chen** [PaperAirplane-Dev-Team/BlackLight#983]
User:HarryChen-SIGKILL- <http://www.github.com>
Feedback:
FFF烧烧烧

**Comment by Harry-Chen** [comment]
回复回复回复

**Comment by Harry-Chen** [comment]
啊啊啊我作业还没做完呢

**Comment by Harry-Chen** [comment]
我的语文作文啊！

**Comment by PeterCxy** [comment]
居然没写作文，差评

**Comment by xavieryao** [comment]
我明天开学

发自我的 iPhone

**Comment by xavieryao** [comment]
@HarryChen-SIGKILL- 我的是因为太长被吞了吗

发自我的 iPhone

**Comment by Harry-Chen** [comment]
哈哈哈哈啊长长长    "html_url": "https://github.com/PaperAirplane-Dev-Team/BlackLight/issues/983#issuecomment-75907526",
    "issue_url": "https://api.github.com/repos/PaperAirplane-Dev-Team/BlackLight/issues/983",
    "id": 75907526,
    "user": {
      "login": "xavieryao",
      "id": 2821051,
      "avatar_url": "https://avatars.githubusercontent.com/u/2821051?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/xavieryao",
      "html_url": "https://github.com/xavieryao",
      "followers_url": "https://api.github.com/users/xavieryao/followers",
      "following_url": "https://api.github.com/users/xavieryao/following{/other_user}",
      "gists_url": "https://api.github.com/users/xavieryao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/xavieryao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/xavieryao/subscriptions",
      "organizations_url": "https://api.github.com/users/xavieryao/orgs",
      "repos_url": "https://api.github.com/users/xavieryao/repos",
      "events_url": "https://api.github.com/users/xavieryao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/xavieryao/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-25T05:23:47Z",
    "updated_at": "2015-02-25T05:23:47Z",
    "body": "@HarryChen-SIGKILL- 我的是因为太长被吞了吗\r\n\r\n发自我的 iPhone\r\n\r\n> 在 2015年2月25日，13:22，Peter Cai <notifications@github.com> 写道：\r\n> \r\n> 居然没写作文，差评\r\n> \r\n> —\r\n> Reply to this email directly or view it o


^你只看得见我^

**Comment by Harry-Chen** [comment]
done it

**Comment by PeterCxy** [comment]
= = 什么鬼,undefined?

**Comment by Harry-Chen** [comment]
@PeterCxy 我用的方法太dirty要求^前后都要有东西
看来要重写一下

**Comment by Harry-Chen** [comment]
^试试看试试看试试看^

**Comment by Harry-Chen** [comment]
^现在应该没问题了哈哈^
